"""empty message

Revision ID: a29dee88ed52
Revises: 4c9fac0b432f
Create Date: 2020-07-13 04:12:24.691569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29dee88ed52'
down_revision = '4c9fac0b432f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('description', sa.String(length=30), nullable=True))
    op.add_column('weather', sa.Column('icon', sa.String(length=30), nullable=True))
    op.add_column('weather', sa.Column('main', sa.String(length=30), nullable=True))
    op.add_column('weather', sa.Column('timezone', sa.Integer(), nullable=True))
    op.add_column('weather', sa.Column('wind_speed', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather', 'wind_speed')
    op.drop_column('weather', 'timezone')
    op.drop_column('weather', 'main')
    op.drop_column('weather', 'icon')
    op.drop_column('weather', 'description')
    # ### end Alembic commands ###
